### ISSUE TITLE
У тебя там, где настройка дисков во 2 пункте есть ошибка

### ISSUE THREAD

**Issue by Loxy01** [abdurrah1m/Professionals_2024#1]
![Снимок экрана 2024-03-20 094845](https://github.com/abdurrah1m/Professionals_2024/assets/99467714/70ef9cb5-bc5e-4ca2-84ea-036df9a8606b)
На снимке в слове была ошибка. Подправишь пожалуйста?

**Comment by abdurrah1m** [comment]
Исправил
